name: "Fivemanage Lite"

services:
  lite-database:
    image: postgres:latest
    container_name: lite-database
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: fivemanage-lite-dev
    ports:
      - "5432:5432"
    volumes:
      - ./.docker/postgres_data:/var/lib/postgresql/data
    networks:
      - fivemanage
  lite-jaeger:
    image: jaegertracing/jaeger:2.4.0 
    container_name: jaeger
    ports:
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "5778:5778"
      - "9411:9411"
  lite-clickhouse:
    image: clickhouse/clickhouse-server:latest
    restart: always
    container_name: lite-clickhouse
    environment:
      CLICKHOUSE_PASSWORD: password
    ports:
      - '18123:8123'
      - '19000:9000'
    volumes:
      - clickhouse-data:/var/lib/clickhouse/
    networks:
      - fivemanage
  lite-minio:
    image: minio/minio:latest
    container_name: lite-minio
    ports:
      - "9000:9000" 
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin123
    command: server /data --console-address ":9001"
    volumes:
      - ./.docker/minio/data:/data
    networks:
      - fivemanage

networks:
  fivemanage:
    driver: bridge


volumes:
  clickhouse-data: { driver: local }
